CREATE DATABASE EMPLOYEE;
USE EMPLOYEE;
CREATE TABLE EMPLOYEE (
    EMPID INT PRIMARY KEY,
    EMP_NAME VARCHAR(50),
    SALARY DECIMAL(10,3)
);
#ADD A NEW COLUMN

ALTER TABLE EMPLOYEE
ADD COLUMN DEPARTMENT VARCHAR(50);
DESCRIBE EMPLOYEE;
ALTER TABLE EMPLOYEE
ADD COLUMN EMAIL VARCHAR(100);
ALTER TABLE EMPLOYEE
ADD COLUMN PHONE_NUMBER VARCHAR(20);
# MODIFY ON EXISTING COLCUMN
ALTER TABLE EMPLOYEE 
MODIFY SALARY DECIMAL(15,5);
DESCRIBE EMPLOYEE;
ALTER TABLE EMPLOYEE 
MODIFY DEPARTMENT VARCHAR(100);
ALTER TABLE EMPLOYEE
MODIFY EMP_NAME VARCHAR(100);
# RENAME A COLUMN
ALTER TABLE EMPLOYEE
RENAME COLUMN NAME TO EMP_NAME;
ALTER TABLE EMPLOYEE
RENAME COLUMN DEPARTMENT_ID TO DEPARTMENT;
ALTER TABLE EMPLOYEE
RENAME COLUMN EMAIL TO EMAIL_COM;
ALTER TABLE EMPLOYEE
ADD COLUMN AGE INT;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT chk_salary
CHECK (SALARY > 0);

ALTER TABLE EMPLOYEE
ADD CONSTRAINT chk_age
CHECK (AGE >= 18);
# DROP A COLUMN 
ALTER TABLE EMPLOYEE 
DROP COLUMN EMAIL_COM;
ALTER TABLE EMPLOYEE
DROP COLUMN PHONE_NUMBER;
ALTER TABLE EMPLOYEE
ADD COLUMN CITY VARCHAR(50) DEFAULT 'Hyderabad';

DESCRIBE EMPLOYEE;
# ADDING PRIMARY KEY
ALTER TABLE EMPLOYEE
ADD PRIMARY KEY (EMPID);
ALTER TABLE EMPLOYEE
ADD COLUMN DEPT_ID INT;

# ADDING UNIQUE CONSTRAINT
ALTER TABLE EMPLOYEE
ADD CONSTRAINT unique_email UNIQUE (EMAIL);
# ADDING NOT NULL CONSTRAINT
ALTER TABLE EMPLOYEE
MODIFY COLUMN EMP_NAME VARCHAR(100) NOT NULL;
# ADDING CHECK CONSTRAINT
INSERT INTO EMPLOYEE (EMPID, EMP_NAME, SALARY, AGE)
VALUES (10, 'Ashok', 30000, 22);
ALTER TABLE EMPLOYEE
ADD CONSTRAINT chk_age
CHECK (AGE >= 18);
# ADDING DEFACULT CONSTRAINT 
ALTER TABLE EMPLOYEE
MODIFY COLUMN CITY VARCHAR(50) DEFAULT 'Hyderabad';
# ADDING FOREGION KEY 
ALTER TABLE EMPLOYEE
ADD CONSTRAINT fk_employee_department
FOREIGN KEY (DEPT_ID)
REFERENCES DEPARTMENT(DEPT_ID);
SELECT * FROM DEPARTMENT;


