CREATE DATABASE COMPANY;
USE COMPANY;
CREATE TABLE EMPLOYEE (
    EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(50),
    SALARY INT,
    DEPT_ID INT
);
INSERT INTO EMPLOYEE
VALUES
(101, 'Ashok', 50000, 1),
(102, 'Rahul', 70000, 2),
(103, 'Priya', 40000, 1),
(104, 'Anil', 30000, 3);
SELECT * FROM EMPLOYEE;
SELECT EMP_NAME, SALARY
FROM EMPLOYEE
WHERE SALARY > ANY (
    SELECT SALARY
    FROM EMPLOYEE
    WHERE DEPT_ID = 1
);
SELECT SALARY
FROM EMPLOYEE
WHERE DEPT_ID = 1;