CREATE DATABASE SETOPERTORS;
USE SETOPERTORS;
#CASE
CREATE TABLE EMPLOYEE (
    EMP_ID INT,
    EMP_NAME VARCHAR(50),
    SALARY INT
);
INSERT INTO EMPLOYEE
VALUES
(101, 'Ashok', 50000),
(102, 'Rahul', 70000),
(103, 'Priya', 30000),
(104, 'Anil', 45000);
SELECT * FROM EMPLOYEE;
# 
SELECT
    EMP_NAME,
    SALARY,
    CASE
        WHEN SALARY >= 60000 THEN 'HIGH'
        WHEN SALARY >= 40000 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS SALARY_LEVEL
FROM EMPLOYEE;




# SET OPERATORS
# UNION
CREATE TABLE EMPLOYEE1 (
    EMP_NAME VARCHAR(50),
    CITY VARCHAR(50)
);
INSERT INTO EMPLOYEE1
VALUES
('Ashok', 'Bangalore'),
('Rahul', 'Hyderabad'),
('Priya', 'Chennai');
CREATE TABLE EMPLOYEE2 (
    EMP_NAME VARCHAR(50),
    CITY VARCHAR(50)
);
INSERT INTO EMPLOYEE2
VALUES
('Priya', 'Chennai'),
('Kiran', 'Mumbai'),
('Anil', 'Delhi');
SELECT EMP_NAME, CITY
FROM EMPLOYEE1

UNION

SELECT EMP_NAME, CITY
FROM EMPLOYEE2;
# UNION ALL
SELECT EMP_NAME, CITY
FROM EMPLOYEE1

UNION ALL

SELECT EMP_NAME, CITY
FROM EMPLOYEE2;
# INTERSECT
SELECT EMP_NAME, CITY
FROM EMPLOYEE1

INTERSECT

SELECT EMP_NAME, CITY
FROM EMPLOYEE2;
# EXCEPT
SELECT EMP_NAME, CITY
FROM EMPLOYEE1

EXCEPT

SELECT EMP_NAME, CITY
FROM EMPLOYEE2;