CREATE DATABASE TYPES;
USE TYPES;
CREATE TABLE DEPARTMENT (
    DEPT_ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(50) NOT NULL
);
INSERT INTO DEPARTMENT
VALUES
(1, 'IT'),
(2, 'HR'),
(3, 'FINANCE');
SELECT * FROM DEPARTMENT;
CREATE TABLE EMPLOYEE (
    EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE,
    AGE INT CHECK (AGE >= 18),
    DEPT_ID INT,

    FOREIGN KEY (DEPT_ID)
    REFERENCES DEPARTMENT(DEPT_ID)
);
# PRIMARY KEY

INSERT INTO EMPLOYEE
VALUES
(101, 'Ashok', 'ashok@gmail.com', 22, 1);
SELECT * FROM EMPLOYEE;
# NOT NULL
INSERT INTO EMPLOYEE
VALUES
(102, 'Rahul', 'rahul@gmail.com', 25, 2);
# UNIQUE
INSERT INTO EMPLOYEE
VALUES
(103, 'Priya', 'priya@gmail.com', 23, 1);
# CHECK 
INSERT INTO EMPLOYEE
VALUES
(104, 'Kiran', 'kiran@gmail.com', 25, 3);
# FOREIGN KEY
INSERT INTO EMPLOYEE
VALUES
(105, 'Ravi', 'ravi@gmail.com', 24, 2);
SELECT * FROM EMPLOYEE;

