CREATE DATABASE DATA;
USE DATA;
CREATE TABLE EMPLOYEE (
    EMP_ID INT,
    EMP_NAME VARCHAR(50),
    JOIN_DATE DATE
);
INSERT INTO EMPLOYEE
VALUES
(101, 'Ashok', '2024-01-15'),
(102, 'Rahul', '2023-06-20'),
(103, 'Priya', '2025-03-10'),
(104, 'Anil', '2022-11-05');
SELECT * FROM EMPLOYEE;
 # CURDATE()
 SELECT curdate();
 SELECT EMPLOYEENAME,CURDATE() AS TODAY
 FROM EMPLOYEE;
 # NOW()
 SELECT NOW();
 
 
 # YEAR
 SELECT EMP_NAME, YEAR(JOIN_DATE) AS JOIN_YEAR
FROM EMPLOYEE;
# MONTH
SELECT EMP_NAME, MONTH(JOIN_DATE) AS JOIN_MONTH
FROM EMPLOYEE;
# DAY
SELECT EMP_NAME, DAY(JOIN_DATE) AS JOIN_DAY
FROM EMPLOYEE;
# DAYNAME
SELECT
    EMP_NAME,
    DAYNAME(JOIN_DATE) AS DAY_NAME
FROM EMPLOYEE; 
# MONTH NAME
SELECT
    EMP_NAME,
    MONTHNAME(JOIN_DATE) AS MONTH_NAME
FROM EMPLOYEE;
# DATE DIFF
SELECT DATEDIFF('2026-08-07', '2026-08-01');
# DATE_ADD()
SELECT DATE_ADD('2026-08-07', INTERVAL 10 DAY);
SELECT
    EMP_NAME,
    DATE_ADD(JOIN_DATE, INTERVAL 1 YEAR) AS ONE_YEAR_LATER
FROM EMPLOYEE;
# DATE_FORMAT()
SELECT
    EMP_NAME,
    DATE_FORMAT(JOIN_DATE, '%d-%m-%Y') AS FORMATTED_DATE
FROM EMPLOYEE;
# LAST DAY
SELECT LAST_DAY('2026-08-07');
# DATE_SUB()
SELECT DATE_SUB('2026-08-07', INTERVAL 10 DAY);
# EXTRACT()
SELECT EXTRACT(YEAR FROM JOIN_DATE)
FROM EMPLOYEE;
SELECT EXTRACT(MONTH FROM JOIN_DATE)
FROM EMPLOYEE;
SELECT EXTRACT(DAY FROM JOIN_DATE)
FROM EMPLOYEE;




 
 
 
 
 # MONTH
 