CREATE DATABASE GROUPBY;
USE GROUPBY;
CREATE TABLE EMPLOYEE (
    EMP_ID INT,
    EMP_NAME VARCHAR(50),
    CITY VARCHAR(50),
    SALARY INT
);
INSERT INTO EMPLOYEE
VALUES
(101, 'Ashok', 'Bangalore', 50000),
(102, 'Rahul', 'Hyderabad', 60000),
(103, 'Priya', 'Chennai', 45000),
(104, 'Anil', 'Hyderabad', 35000),
(105, 'Kiran', 'Bangalore', 55000);
SELECT * FROM EMPLOYEE;
SELECT CITY FROM EMPLOYEE
GROUP BY CITY;
# COUNT
SELECT CITY, COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEE
GROUP BY CITY;
# SUM 
SELECT CITY, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEE
GROUP BY CITY; 
# AVG
SELECT CITY,AVG(SALARY) AS TOTAL_SALARY
FROM EMPLOYEE
GROUP BY CITY;
# MIN
SELECT CITY,MIN(SALARY) AS TOTAL_SALARY
FROM EMPLOYEE
GROUP BY CITY;
# MAX
SELECT CITY,MAX(SALARY) AS TOTAL_SALARY
FROM EMPLOYEE
GROUP BY CITY;
# GROUP BY WITH WHERE
SELECT CITY, COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEE
WHERE SALARY > 40000
GROUP BY CITY;
# GROUP HAVING WITH HAVING
SELECT CITY, COUNT(*) AS TOTAL
FROM EMPLOYEE
WHERE SALARY > 40000
GROUP BY CITY
HAVING COUNT(*) >= 2;
# GROUP BY WITH ORDER
SELECT CITY, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEE
GROUP BY CITY
ORDER BY TOTAL_SALARY DESC;
# GROUP BY WITH ORDER AND LIMIT
SELECT CITY, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEE
GROUP BY CITY
ORDER BY TOTAL_SALARY DESC
LIMIT 1;