CREATE DATABASE JOINS;
USE JOINS;
CREATE TABLE DEPARTMENT (
    DEPT_ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(50)
);
INSERT INTO DEPARTMENT
VALUES
(1, 'IT'),
(2, 'HR'),
(3, 'FINANCE'),
(4, 'SALES');
SELECT * FROM DEPARTMENT;
CREATE TABLE EMPLOYEE (
    EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(50),
    SALARY INT,
    DEPT_ID INT,
    FOREIGN KEY (DEPT_ID)
        REFERENCES DEPARTMENT(DEPT_ID)
);
INSERT INTO EMPLOYEE
VALUES
(101, 'Ashok', 50000, 1),
(102, 'Rahul', 60000, 2),
(103, 'Priya', 45000, 1),
(104, 'Anil', 35000, 3),
(105, 'Kiran', 40000, NULL);
SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;
# INNER JOINS
SELECT
    E.EMP_ID,
    E.EMP_NAME,
    E.SALARY,
    D.DEPT_NAME
FROM EMPLOYEE E
INNER JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;
# LEFT JOINS
SELECT
    E.EMP_ID,
    E.EMP_NAME,
    E.SALARY,
    D.DEPT_NAME
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;
# RIGHT JOINS
SELECT
    E.EMP_ID,
    E.EMP_NAME,
    D.DEPT_ID,
    D.DEPT_NAME
FROM EMPLOYEE E
RIGHT JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;
# FULL JOINS
SELECT
    E.EMP_ID,
    E.EMP_NAME,
    D.DEPT_NAME
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID

UNION

SELECT
    E.EMP_ID,
    E.EMP_NAME,
    D.DEPT_NAME
FROM EMPLOYEE E
RIGHT JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;
# CROSS JOINS
SELECT
    E.EMP_NAME,
    D.DEPT_NAME
FROM EMPLOYEE E
CROSS JOIN DEPARTMENT D;
# SELF JOINS
CREATE TABLE EMP (
    EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(50),
    MANAGER_ID INT
);
