CREATE DATABASE AGGREGATE;
USE AGGREGATE;
CREATE TABLE EMPLOYEE (
    EMP_ID INT,
    EMP_NAME VARCHAR(50),
    CITY VARCHAR(50),
    SALARY INT
);
INSERT INTO EMPLOYEE
VALUES
(101,'Ashok','Bangalore',50000),
(102,'Rahul','Hyderabad',60000),
(103,'Priya','Chennai',45000),
(104,'Anil','Hyderabad',35000),
(105,'Kiran','Mumbai',55000);
SELECT * FROM EMPLOYEE;
# ORDER
SELECT *
FROM EMPLOYEE
ORDER BY SALARY ASC;
SELECT * FROM EMPLOYEE 
ORDER BY EMP_ID ASC;
SELECT *
FROM EMPLOYEE
ORDER BY SALARY DESC;
# LIMIT
SELECT * FROM EMPLOYEE
LIMIT 3;
SELECT * FROM EMPLOYEE
ORDER BY SALARY DESC;
SELECT * FROM employee
ORDER BY SALARY ASC;
SELECT *
FROM EMPLOYEE
ORDER BY SALARY DESC
LIMIT 1;
# AGGREGATE FUNCTIONS
# COUNT
SELECT COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEE;
# SUM
SELECT SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEE;
# AVERAGE
SELECT AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEE;
# MAX
SELECT MAX(SALARY) AS HIGHEST_SALARY
FROM EMPLOYEE;
# MIN
SELECT MIN(SALARY) AS LOWEST_SALARY
FROM EMPLOYEE;

