CREATE DATABASE STRINGFUNCTIONS;
USE STRINGFUNCTIONS;
CREATE TABLE EMPLOYEE (
    EMP_ID INT,
    EMP_NAME VARCHAR(50),
    CITY VARCHAR(50)
);
INSERT INTO EMPLOYEE
VALUES
(101, 'Ashok', 'Bangalore'),
(102, 'Rahul', 'Hyderabad'),
(103, 'Priya', 'Chennai');
SELECT * FROM EMPLOYEE;
# CONCAT()
SELECT CONCAT(EMP_NAME, ' - ', CITY) AS DETAILS
FROM EMPLOYEE;
# UPPER()
SELECT UPPER(EMP_NAME) AS NAME
FROM EMPLOYEE;
# LOWER()
SELECT LOWER(EMP_NAME) AS NAME
FROM EMPLOYEE;
# LENGTH()
SELECT EMP_NAME, LENGTH(EMP_NAME) AS NAME_LENGTH
FROM EMPLOYEE;
# CHAR_LENGTH()
SELECT EMP_NAME, CHAR_LENGTH(EMP_NAME) AS NAME_LENGTH
FROM EMPLOYEE;
# SUBSTRING
SELECT SUBSTRING(EMP_NAME, 1, 3) AS SHORT_NAME
FROM EMPLOYEE;
# LEFT
SELECT LEFT(EMP_NAME, 2) AS FIRST_TWO
FROM EMPLOYEE;
# RIGHT
SELECT RIGHT(EMP_NAME, 2) AS LAST_TWO
FROM EMPLOYEE;
# REPLACE
SELECT REPLACE(CITY, 'Bangalore', 'Hyderabad') AS NEW_CITY
FROM EMPLOYEE;
# REVERSE
SELECT REVERSE(EMP_NAME) AS REVERSED_NAME
FROM EMPLOYEE;
 


