CREATE DATABASE BANK;
USE BANK;
CREATE TABLE ACCOUNT (
    ACCOUNT_ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    BALANCE INT
);
INSERT INTO ACCOUNT
VALUES
(101, 'Ashok', 10000),
(102, 'Rahul', 5000);
# COMMIT
SELECT * FROM ACCOUNT;
START TRANSACTION;
UPDATE ACCOUNT
SET BALANCE = BALANCE - 2000
WHERE ACCOUNT_ID = 101;
UPDATE ACCOUNT
SET BALANCE = BALANCE + 2000
WHERE ACCOUNT_ID = 102;
SELECT * FROM ACCOUNT;

# ROLL BACK
START TRANSACTION;
UPDATE ACCOUNT
SET BALANCE = BALANCE - 5000
WHERE ACCOUNT_ID = 101;
SELECT * FROM ACCOUNT;

# SAVE POINT
START TRANSACTION;
UPDATE ACCOUNT
SET BALANCE = BALANCE - 1000
WHERE ACCOUNT_ID = 101;
SAVEPOINT point1;
UPDATE ACCOUNT
SET BALANCE = BALANCE + 1000
WHERE ACCOUNT_ID = 102;
ROLLBACK TO SAVEPOINT point1;

