CREATE DATABASE VIEWS;
USE VIEWS;
CREATE TABLE DEPARTMENT (
    DEPT_ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(50)
);
INSERT INTO DEPARTMENT
VALUES
(1, 'IT'),
(2, 'HR'),
(3, 'FINANCE');
CREATE TABLE EMPLOYEE (
    EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(50),
    SALARY INT,
    DEPT_ID INT,
    FOREIGN KEY (DEPT_ID)
        REFERENCES DEPARTMENT(DEPT_ID)
);
INSERT INTO EMPLOYEE
VALUES
(101, 'Ashok', 50000, 1),
(102, 'Rahul', 70000, 2),
(103, 'Priya', 45000, 1),
(104, 'Anil', 35000, 3);
CREATE VIEW EMPLOYEE_DETAILS AS
SELECT EMP_ID, EMP_NAME, SALARY
FROM EMPLOYEE;
SELECT * FROM EMPLOYEE_DETAILS;
#  VIEWS WHERE
SELECT *
FROM EMPLOYEE_DETAILS
WHERE SALARY > 40000;
# VIEWS JOINS
CREATE VIEW EMPLOYEE_DEPARTMENT AS
SELECT
    E.EMP_ID,
    E.EMP_NAME,
    E.SALARY,
    D.DEPT_NAME
FROM EMPLOYEE E
JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID;
SELECT * FROM EMPLOYEE_DEPARTMENT;
# CHANGE VIEWS
CREATE OR REPLACE VIEW EMPLOYEE_DETAILS AS
SELECT EMP_ID, EMP_NAME, SALARY
FROM EMPLOYEE
WHERE SALARY >= 50000;
SELECT * FROM EMPLOYEE_DETAILS;
DROP VIEW EMPLOYEE_DETAILS;

# SUBQUERIES
SELECT *
FROM EMPLOYEE
WHERE SALARY > (
    SELECT AVG(SALARY)
    FROM EMPLOYEE
);
# SUBQUERY
SELECT EMP_NAME, SALARY
FROM EMPLOYEE
WHERE SALARY = (
    SELECT MAX(SALARY)
    FROM EMPLOYEE
);
# SUBQUERY MIN
SELECT EMP_NAME, SALARY
FROM EMPLOYEE
WHERE SALARY = (
    SELECT MIN(SALARY)
    FROM EMPLOYEE
);
# SUBQUERY IN
SELECT EMP_NAME, SALARY
FROM EMPLOYEE
WHERE DEPT_ID IN (
    SELECT DEPT_ID
    FROM DEPARTMENT
    WHERE DEPT_NAME IN ('IT', 'HR')
);
# SUBQUERY EXPECT
SELECT DEPT_NAME
FROM DEPARTMENT D
WHERE EXISTS (
    SELECT 1
    FROM EMPLOYEE E
    WHERE E.DEPT_ID = D.DEPT_ID
);
# SUBQUERY WITH ANY
SELECT EMP_NAME, SALARY
FROM EMPLOYEE
WHERE SALARY > ANY (
    SELECT SALARY
    FROM EMPLOYEE
    WHERE DEPT_ID = 1
);
# SUBQUERY WITH ALL
SELECT EMP_NAME, SALARY
FROM EMPLOYEE
WHERE SALARY > ALL (
    SELECT SALARY
    FROM EMPLOYEE
    WHERE DEPT_ID = 1
);
# Types of Subqueries
# Single-row subquery
SELECT MAX(SALARY)
FROM EMPLOYEE;
# Multiple-row subquery
SELECT DEPT_ID
FROM DEPARTMENT
WHERE DEPT_NAME IN ('IT', 'HR');
# Multiple-column subquery
SELECT DEPT_ID, DEPT_NAME
FROM DEPARTMENT;
# Correlated subquery
SELECT E.EMP_NAME, E.SALARY
FROM EMPLOYEE E
WHERE E.SALARY > (
    SELECT AVG(E2.SALARY)
    FROM EMPLOYEE E2
    WHERE E2.DEPT_ID = E.DEPT_ID
);
